### ISSUE TITLE
Uncaught SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by ofadam** [fbsamples/live-comments-teleprompter#13] opened 2018-05-17 19:13 UTC
I went through the process described in the docs and everything ran without error. But when trying to access it on our web server, I get the following errors:

Uncaught SyntaxError: Unexpected identifier in index-bundle.js:55 
Uncaught SyntaxError: Unexpected identifier in teleprompter-bundle.js:55

http://pjstarpeoria.com/fblive/

**Comment by bradisbell** [comment] 2018-05-17 21:24
The line that's throwing the error is an `import` statement.  It seems Babel isn't loading these modules for some reason.

Can you run the following:

```
npm ls > npmls.txt
```

Then, upload that file or paste its contents here?

Also, can you confirm you're running `npm run build` from the project's root directory?

**Comment by ofadam** [comment] 2018-05-17 21:38
[npmls.txt](https://github.com/fbsamples/live-comments-teleprompter/files/2014816/npmls.txt)

And yep, running it from the project's root.

**Comment by bradisbell** [comment] 2018-05-18 00:26
Hmm, I don't see any differences between your packages and mine.  The only difference I see is platform.  (I'm on Windows.)

The only thing I can think of is that something is getting messed up with the exclusion in `webpack.config.js`.  Try replacing that whole `module` property with this:

```
  module: {
    loaders: [
      {
        test: /.*/,
        loader: 'babel-loader'
      }
    ],
  },
```

**Comment by ofadam** [comment] 2018-05-18 18:36
That didn't do the trick either...

The browser is hanging up on line 55 of index-bundle.js: 
	import EventEmitter from 'event-emitter';

**Comment by bradisbell** [comment] 2018-05-22 22:03
The issue is that this line shouldn't exist in the output.  Babel should be injecting all the modules directly into this bundle, but that doesn't seem to be happen.  I'm not sure what the actual issue is though.

What version of Node are you using?  `node -v`  I'm not sure what else to suggest, other than that there's some issue with the Babel loader.

**Comment by bradisbell** [comment] 2018-05-30 20:51
I'm going to close this issue for now, as we haven't been able to reproduce it in any environment we tested.  If you or anyone is able to reproduce it elsewhere or figure out what the difference is, please comment and we can re-open.

**Closed as completed by bradisbell** 2018-05-30 20:51 UTC

**Comment by FildonPrime** [comment] 2019-03-23 15:17
Same issue, as described above.
![image](https://user-images.githubusercontent.com/29151195/54867941-d54fc800-4dac-11e9-9982-11f341e35d46.png)

Edit : Node version : v11.12.0
